const prueba =()=>{
    suma()
}
const suma = ()=>{
    return 4+b
}

try{
    prueba()
}catch(err){
    console.error("error encontrado");
    console.error(err.message);
}